# Generated by Django 5.0.3 on 2024-03-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
