# Generated by Django 5.0.3 on 2024-03-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0006_users_reset_password_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
