# Generated by Django 5.0.3 on 2024-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0008_notify_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('description_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
            ],
        ),
    ]
